spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8a405.p.ssafy.io:3306/swing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swing
    password: asdf1234
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments : true
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

file:
  path: C:/images
cloud:
  aws:
    credentials:
      access-key: [ACCESS-KEY]
      secret-key: [SECRET-KEY]
    s3:
      bucket : [BUCKET]
    region:
      static: ap-northeast-2
    stack:
      auto: false

